#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2026 The Thorium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""
Extract safe_browsing-related hunks from ungoogled-chromium source patches.

This module scans all patches in ungoogled-chromium-windows's core patch
directory and extracts content related to safe_browsing into a single
auto-generated patch file.

Extraction rules (all case-insensitive):
  1. File-path rule: If the patched file path contains '/safe_browsing/', all
     hunks from that file are included.
  2. Hunk-content rule: If a hunk (including its @@-header) contains
     'SafeBrowsing' or 'Safe_Browsing', only that hunk is included.
  3. Both rules are combined: a hunk is included if either rule matches.

The output is written to
  patches/thorium/fixes/autogenerated_remove-safebrowsing-prefs-deps.patch

The output file is cleared before each run.

Usage (standalone):
  python3 patch_scripts/extract_safebrowsing_patches.py
  python3 patch_scripts/extract_safebrowsing_patches.py --source-patch <path>

Integration with build.py:
  from patch_scripts import extract_safebrowsing_patches
  extract_safebrowsing_patches.run_extraction()

To extend with new rules:
  - Add a new rule function matching the (_check_fn) signature.
  - Pass it in the rules list to _extract_relevant_hunks().
"""

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Callable, List, Optional, Tuple

# Use ungoogled-chromium's logger hierarchy so build.py's handler applies.
logger = logging.getLogger('ungoogled.extract_safebrowsing_patches')

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
_ROOT_DIR = _SCRIPT_DIR.parent  # thorium_autobuild_win/

_SOURCE_PATCH_FILE = (
    _ROOT_DIR / 'ungoogled-chromium-windows' / 'ungoogled-chromium' /
    'patches' / 'core' / 'ungoogled-chromium' /
    'remove-unused-preferences-fields.patch'
)
_OUTPUT_PATCH = (
    _ROOT_DIR / 'patches' / 'thorium' / 'fixes' /
    'autogenerated_remove-safebrowsing-prefs-deps.patch'
)
_SERIES_FILE = _ROOT_DIR / 'patches' / 'series'

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

# A hunk is a string that starts with '@@ -' and includes all following lines
# until the next hunk or end of section.
Hunk = str

# A file section: (file_path, [hunk, ...])
FileSection = Tuple[str, List[Hunk]]

# A rule check function: (file_path, hunk_text) -> bool
# Return True if the hunk should be included.
_CheckFn = Callable[[str, str], bool]

# ---------------------------------------------------------------------------
# Patch parser
# ---------------------------------------------------------------------------

_HUNK_HEADER_RE = re.compile(r'^@@ -\d+(?:,\d+)? \+\d+(?:,\d+)? @@')


def parse_patch_file(filepath: Path) -> List[FileSection]:
    """
    Parse a unified-diff patch file into file sections and hunks.

    Returns a list of (file_path, [hunk_text, ...]) where each hunk_text
    includes the '@@ -... +... @@' header line and its body lines.
    Comment lines (starting with '#') are discarded.
    """
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    # Normalise line endings to \n for parsing; keep original for output.
    lines = content.splitlines(keepends=True)

    sections: List[FileSection] = []

    i = 0
    while i < len(lines):
        line = lines[i]

        # Skip comment / blank lines at top level (between sections).
        if line.startswith('#') or line.strip() == '':
            i += 1
            continue

        # Look for '--- a/' which starts a new file section.
        if line.startswith('--- a/'):
            old_path = line.rstrip('\n\r')
            i += 1
            if i >= len(lines):
                break
            new_path = lines[i].rstrip('\n\r')
            i += 1

            # Extract normalised file path.
            # Standard unified-diff: '--- a/path' or '--- b/path'.
            # Strip the leading 'a/' or 'b/' prefix.
            raw = old_path[4:].strip()  # after '--- '
            if raw.startswith('a/') or raw.startswith('b/'):
                file_path = raw[2:]
            else:
                file_path = raw

            # Collect hunks in this section.
            hunks: List[str] = []
            current_hunk: List[str] = []

            while i < len(lines):
                next_line = lines[i]

                # Next file section -> stop.
                if next_line.startswith('--- a/'):
                    break

                # Comment at top level (between hunks) -> skip.
                if next_line.startswith('#') and not current_hunk:
                    i += 1
                    continue

                stripped = next_line.rstrip('\n\r')

                if _HUNK_HEADER_RE.match(stripped):
                    # Flush previous hunk.
                    if current_hunk:
                        hunks.append(''.join(current_hunk))
                    current_hunk = [next_line]
                elif current_hunk:
                    # Inside an active hunk.
                    current_hunk.append(next_line)

                i += 1

            # Flush last hunk.
            if current_hunk:
                hunks.append(''.join(current_hunk))

            if hunks:
                sections.append((file_path, hunks))
        else:
            # Unrecognised top-level line (e.g. trailing comments).
            i += 1

    return sections


# ---------------------------------------------------------------------------
# Built-in rule check functions
# ---------------------------------------------------------------------------


def _rule_safe_browsing_path(file_path: str, _hunk: str) -> bool:
    """Rule 1: file path contains '/safe_browsing/' (case-insensitive)."""
    return '/safe_browsing/' in file_path.lower()


def _rule_safe_browsing_keywords(_file_path: str, hunk: str) -> bool:
    """
    Rule 2: changed lines (+ or -) contain safe_browsing-related keywords
    (case-insensitive). Context lines (starting with space) are ignored.
    """
    HUNK_KEYWORDS = (
        'safebrowsing',
        'safe_browsing',
        'ukm_pref',
        'getextendedreportingprefnam',
        # 'advancedprotection',
        # 'passwordprotection',
    )
    for line in hunk.splitlines():
        if line.startswith('+') or line.startswith('-'):
            lower = line.lower()
            if any(keyword in lower for keyword in HUNK_KEYWORDS):
                return True
    return False


# ---------------------------------------------------------------------------
# Core extraction logic
# ---------------------------------------------------------------------------

# Default set of rules -- extend by appending to this list.
_DEFAULT_RULES: List[_CheckFn] = [
    _rule_safe_browsing_path,
    _rule_safe_browsing_keywords,
]


def _extract_relevant_hunks(
    sections: List[FileSection],
    rules: Optional[List[_CheckFn]] = None,
) -> List[FileSection]:
    """
    Filter patch sections to only hunks matching any of the given rules.

    When no rules match any hunk in a section, the section is omitted.
    When a file-path rule (rule 1) matches, **all** hunks for that file are
    kept.  Otherwise only hunks whose content matches a rule are kept.
    """
    if rules is None:
        rules = _DEFAULT_RULES

    result: List[FileSection] = []

    for file_path, hunks in sections:
        # Check path-based rules first.
        path_matches = any(
            fn(file_path, '') for fn in rules
            if fn is not _rule_safe_browsing_keywords
        )
        if path_matches:
            # Rule 1 -- keep all hunks for this file.
            result.append((file_path, hunks))
            continue

        # Otherwise, check each hunk individually.
        relevant_hunks = [
            h for h in hunks
            if any(fn(file_path, h) for fn in rules)
        ]
        if relevant_hunks:
            result.append((file_path, relevant_hunks))

    return result


# ---------------------------------------------------------------------------
# Output assembly
# ---------------------------------------------------------------------------

def _assemble_patch(sections: List[FileSection]) -> str:
    """
    Assemble a unified-diff patch string from extracted sections.
    """
    parts: List[str] = []

    for file_path, hunks in sections:
        # Write file headers.
        parts.append(f'--- a/{file_path}\n')
        parts.append(f'+++ b/{file_path}\n')
        for hunk in hunks:
            parts.append(hunk)
            if not hunk.endswith('\n'):
                parts.append('\n')

    return ''.join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_extraction(
    source_patch: Optional[Path] = None,
    output_file: Optional[Path] = None,
    rules: Optional[List[_CheckFn]] = None,
) -> bool:
    """
    Run the full extraction pipeline.

    Steps:
      1. Clear the output file.
      2. Parse the source patch file into sections & hunks.
      3. Apply extraction rules.
      4. Write matched hunks to *output_file*.

    Returns ``True`` if at least one hunk was written (output non-empty).

    This function is safe to call from ``build.py`` -- it always starts from
    a clean slate.
    """
    if source_patch is None:
        source_patch = _SOURCE_PATCH_FILE
    if output_file is None:
        output_file = _OUTPUT_PATCH

    # 1. Clear output.
    output_file.parent.mkdir(parents=True, exist_ok=True)
    # Note: use write_bytes() throughout to avoid Windows text-mode
    # \n -> \r\n auto-conversion, which would double our explicit CRLF.
    output_file.write_bytes(b'')

    # 2. Parse source patch file.
    if not source_patch.exists():
        logger.warning('source patch not found: %s', source_patch)
        return False

    sections = parse_patch_file(source_patch)

    # 3-4. Parse & filter.
    all_extracted: List[FileSection] = []
    relevant = _extract_relevant_hunks(sections, rules=rules)
    all_extracted.extend(relevant)

    if not all_extracted:
        logger.warning('no relevant patches found in %s', source_patch)
        return False

    # 5. Write output.
    patch_text = _assemble_patch(all_extracted)
    # Write with CRLF line endings (required by patch.exe on Windows).
    # Use write_bytes() to bypass text-mode \n -> \r\n auto-conversion;
    # otherwise we get \r\r\n on Windows CMD.
    patch_bytes = patch_text.replace('\n', '\r\n').encode('utf-8')
    output_file.write_bytes(patch_bytes)

    hunk_count = sum(len(hunks) for _, hunks in all_extracted)
    logger.info('%d file sections, %d hunks -> %s',
                len(all_extracted), hunk_count, output_file)
    return True


def ensure_in_series(series_file: Optional[Path] = None) -> bool:
    """
    Ensure the auto-generated patch is listed in the series file.

    If the output patch is non-empty and not already in the series, it is
    inserted at the top (so it applies before all other patches).

    Returns ``True`` if the series was modified.
    """
    if series_file is None:
        series_file = _SERIES_FILE

    if not _OUTPUT_PATCH.exists() or _OUTPUT_PATCH.stat().st_size == 0:
        return False  # nothing to register

    entry = 'thorium/fixes/autogenerated_remove-safebrowsing-prefs-deps.patch'

    if not series_file.exists():
        return False

    content = series_file.read_text(encoding='utf-8')
    # Check if already present (as exact line or commented out).
    already_present = any(
        line.strip() == entry for line in content.splitlines()
    )
    if already_present:
        return False

    # Insert at top, after any leading comment block.
    lines = content.splitlines(keepends=True)
    insert_idx = 0
    for i, line in enumerate(lines):
        if line.startswith('#') or line.strip() == '':
            insert_idx = i + 1
        else:
            break

    lines.insert(insert_idx, f'{entry}\n')
    series_file.write_text(''.join(lines), encoding='utf-8')
    logger.info('added %s to %s', entry, series_file)
    return True


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description='Extract safe_browsing-related patches from '
                    'ungoogled-chromium source patches.')
    parser.add_argument(
        '--source-patch',
        type=Path,
        default=_SOURCE_PATCH_FILE,
        help=f'Source patch file to extract from '
             f'(default: {_SOURCE_PATCH_FILE})',
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=_OUTPUT_PATCH,
        help=f'Output patch file path (default: {_OUTPUT_PATCH})',
    )
    parser.add_argument(
        '--ensure-series',
        action='store_true',
        help='Also ensure the output patch is registered in patches/series',
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format='%(levelname)s %(message)s',
        stream=sys.stderr,
    )

    ok = run_extraction(
        source_patch=args.source_patch,
        output_file=args.output,
    )

    if ok and args.ensure_series:
        ensure_in_series()

    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
