name: build-arm64
on:
  workflow_dispatch:
#  push:
#    tags:
#      - '*'

permissions:
  contents: read

concurrency:
  group: build-arm64-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ARM64 build temporarily disabled
  prepare:
    if: false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Restore source cache
        id: source-cache
        uses: actions/cache@v4
        with:
          path: C:\tbw\build\src
          key: thorium-src-arm64-${{ github.sha }}
      - name: Prepare Chromium source
        if: ${{ steps.source-cache.outputs.cache-hit != 'true' }}
        shell: pwsh
        run: python build.py --ci --prepare-only --arm
        working-directory: C:\tbw

  build:
    needs: prepare
    uses: ./.github/workflows/reusable-build.yml
    with:
      arm: true
      simd: sse3
      cache-key: thorium-src-arm64-${{ github.sha }}
      artifact-name: thorium-arm64
    secrets:
      GOOGLE_API_KEY: ${{ secrets['GOOGLE_API_KEY'] }}
      GOOGLE_DEFAULT_CLIENT_ID: ${{ secrets['GOOGLE_DEFAULT_CLIENT_ID'] }}
      GOOGLE_DEFAULT_CLIENT_SECRET: ${{ secrets['GOOGLE_DEFAULT_CLIENT_SECRET'] }}
