name: build-x64-avx2
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: build-x64-avx2-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Restore source cache
        id: source-cache
        uses: actions/cache@v5
        with:
          path: C:\tbw\build\src
          key: thorium-src-${{ github.sha }}
      - name: Prepare Chromium source
        if: ${{ steps.source-cache.outputs.cache-hit != 'true' }}
        shell: pwsh
        run: python build.py --ci --prepare-only
        working-directory: C:\tbw

  build:
    needs: prepare
    uses: ./.github/workflows/reusable-build.yml
    with:
      simd: avx2
      cache-key: thorium-src-${{ github.sha }}
    secrets:
      GOOGLE_API_KEY: ${{ secrets['GOOGLE_API_KEY'] }}
      GOOGLE_API_KEY_REMOTING: ${{ secrets['GOOGLE_API_KEY_REMOTING'] }}
      GOOGLE_API_KEY_SODA: ${{ secrets['GOOGLE_API_KEY_SODA'] }}
      GOOGLE_DEFAULT_CLIENT_ID: ${{ secrets['GOOGLE_DEFAULT_CLIENT_ID'] }}
      GOOGLE_CLIENT_ID_REMOTING: ${{ secrets['GOOGLE_CLIENT_ID_REMOTING'] }}
      GOOGLE_DEFAULT_CLIENT_SECRET: ${{ secrets['GOOGLE_DEFAULT_CLIENT_SECRET'] }}
      GOOGLE_CLIENT_SECRET_REMOTING: ${{ secrets['GOOGLE_CLIENT_SECRET_REMOTING'] }}
